Patch release with fix for https://github.com/brianguenter/FastDifferentiation.jl/pull/68#issue-2218735778 Type inference is not precise enough when performing arithmetic operations on matrices of Node. These all return Matrix{Any} instead of Matrix{Node} which can cause errors when trying to compute Jacobians.
This patch will fix the problem by declaring the return type of simplify_check_cache to give the compiler enough information to infer correctly.

Here is an example of the problem:

julia> @variables a1 a2 b1 b2 c1 c2 d1 d2
d2

julia> thing1 = [a1 b1; c1 d1]
2×2 Matrix{FastDifferentiation.Node}:
 a1  b1
 c1  d1

julia> thing2 = [a2 b2; c2 d2]
2×2 Matrix{FastDifferentiation.Node}:
 a2  b2
 c2  d2

julia>

julia> thing3 = thing1 * thing2
2×2 Matrix{Any}:
 ((a1 * a2) + (b1 * c2))  ((a1 * b2) + (b1 * d2))
 ((c1 * a2) + (d1 * c2))  ((c1 * b2) + (d1 * d2))

julia> jacobian(thing3, [a1, c2])
ERROR: MethodError: no method matching jacobian(::Matrix{Any}, ::Vector{FastDifferentiation.Node})

Closest candidates are:
  jacobian(::AbstractVector{T}, ::AbstractVector{S}) where {T<:FastDifferentiation.Node, S<:FastDifferentiation.Node}
   @ FastDifferentiation C:\Users\seatt\.julia\dev\FastDifferentiation\src\Jacobian.jl:90

Stacktrace:
 [1] top-level scope
   @ REPL[13]:1

julia> jacobian(vec(thing3), [a1, c2])
ERROR: MethodError: no method matching jacobian(::Vector{Any}, ::Vector{FastDifferentiation.Node})